### ISSUE TITLE
Would love a working example.

### ISSUE THREAD

**Issue by rlam3** [nuxt-community/google-adsense-module#12]
Would love a working example as reference.

Been trying to get mine code working but it doesn't seem to work show anything in page. 
It shows up the tag of 

tag of `<adsbygoogle/>`

Console error:
```
[Vue warn]: Unknown custom element: <adsbygoogle> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

but nothing to show for it.

Thanks! 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/google-adsense-module/issues/c3">#c3</a>)</em></sub></div>

**Comment by farnabaz** [comment]
There is a simple example under [`example`](https://github.com/nuxt-community/google-adsense-module/tree/master/example) directory
