### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by AlexLomm** [nuxt-community/google-adsense-module#13]
Node: **v8.9.4**
npm: **v5.6.0**
google-adsense: **v1.1.3**

I'm getting the following error when running `npm run dev` against my nuxt project:

<img width="424" alt="screen shot 2018-01-23 at 1 10 49 pm" src="https://user-images.githubusercontent.com/11467210/35267169-ddd0ad76-003e-11e8-8de5-ed075290712b.png">

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/google-adsense-module/issues/c5">#c5</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. This problem is probably because nuxt couldn't find adsense module. Would you please share nuxt.config.js and also ensuring module is probably installed?

**Comment by AlexLomm** [comment]
Thanks for replying. Here is the `nuxt.config.js`: 

<img width="890" alt="screen shot 2018-01-23 at 1 31 19 pm" src="https://user-images.githubusercontent.com/11467210/35268200-ec9571fe-0041-11e8-9d60-ea215bcccf01.png">

Also, I've installed the package by running `npm install @nuxtjs/google-adsense`. Is there something more I should've done?

**Comment by jaubut** [comment]
Did you found a solution ? I have the same error with others modules..

**Comment by matusmarcin** [comment]
I ran into the same error message when trying to use `@nuxtjs/google-analytics`, however it's just my own silliness.

Snippet from my `nuxt.config.js` with the error present:

```javascript
  modules: [
    '@nuxtjs/google-analytics', {
      id: 'UA-xxx-2'
    },
    'nuxt-auth',
    '@nuxtjs/axios'
  ],
```

This is the **fix**: 

When trying to load a module like this, along with the property, it needs to be wrapped in `[]` to make an array. 

```javascript
  modules: [
    [ '@nuxtjs/google-analytics', {
      id: 'UA-xxx-2'
    } ],
    'nuxt-auth',
    '@nuxtjs/axios'
  ],
```

@AlexLomm in your case, try this:

```javascript
  modules: [
    [ '@nuxtjs/google-adsense', {
      id: '<<< id >>>'
    } ]
  ],
```
