### ISSUE TITLE
[Vue warn]: You are using the runtime-only build...

### ISSUE THREAD

**Issue by AlexLomm** [nuxt-community/google-adsense-module#14]
I'm getting the following error when trying to use this package (*with nuxt*):

<img width="545" alt="screen shot 2018-01-23 at 10 16 44 pm" src="https://user-images.githubusercontent.com/11467210/35292822-2bb160c0-008b-11e8-8802-d4cdbfe6f8d4.png">

The issue is arised because templates should be precompiled before releasing dist, as is explained in the following issue: https://github.com/nuxt/nuxt.js/issues/1142#issuecomment-317273189

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/google-adsense-module/issues/c8">#c8</a>)</em></sub></div>

**Comment by tmorehouse** [comment]
The adsense module uses a render function and not a string template.
