### ISSUE TITLE
nuxt generate 

### ISSUE THREAD

**Issue by kruny1001** [nuxt-community/google-adsense-module#16]
It seems spa version doesn't work. 
adsbygoogle.push() error: Only one 'enable_page_level_ads' allowed per page.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/google-adsense-module/issues/c6">#c6</a>)</em></sub></div>

**Comment by Coletrane** [comment]
can confirm I'm seeing this issue too. The `<script>` tag for is getting added twice, once in head, once in body. I downgraded to version 1.1.2 and it fixed the issue.

**Comment by Teranode** [comment]
any solution for this?

**Comment by nmbakfm** [comment]
I got this issue too.

**Comment by tehfonsi** [comment]
I worked around this issue using this:
```
if (process.browser && (!window.adsbygoogle || !window.adsbygoogle.loaded)) {
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-5488680154292935",
        enable_page_level_ads: true
      });
    }
```
Open for ideas if someone has a better solution.

**Comment by lluishi93** [comment]
@tehfonsi Where did you place that code?

**Comment by tiofabby** [comment]
I had same issue, I had to remove @nuxtjs/google-adsense from nuxt-config and load script manually with something like below:

```
let script = document.createElement('script')
script.setAttribute('data-ad-client', 'ca-pub-XXXXXXXXXX')
script.setAttribute('src', 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js')
document.head.appendChild(script )
```

**Comment by bengineer19** [comment]
This seems to be a pretty important issue as this module is essentially unusable in its current state.

Upgrading Nuxt to > 2.10 fixed the bug when running in dev mode and SSR mode (ie it works fine for `npm run dev` and `npm run build && npm run start`).
![image](https://user-images.githubusercontent.com/6606828/79042255-e94fad00-7bed-11ea-9221-bf20aefe45c1.png)


**However the issue still remains when using nuxt generate.** Given that many Nuxt sites are deployed entirely using this mode in production, this issue is fairly major for this module.

I'm happy to assist with a fix if a maintainer can provide some guidance.

**Comment by agustin96** [comment]
@kruny1001 @bengineer19 @tiofabby hi, i found a solution, no need for this module as we can use the head property. just copy this to nuxt.config.js

[https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-head](url)

```
head: {
    script:  #[
      {
        "data-ad-client": "ca-pub-xxxxxx",
        src: "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",
      },
    ],
  },
```

**Comment by farnabaz** [comment]
This should fix in the latest beta release. [v1.3.0-rc.1](https://github.com/nuxt-community/google-adsense-module/releases/tag/v1.3.0-rc.1)  
Really appreciate if you can confirm the fix 🙂

**Comment by farnabaz** [comment]
Just released [v1.3.0](https://github.com/nuxt-community/google-adsense-module/releases/tag/v1.3.0).

I close this issue, feel free to reopen it if issue exists in new version

**Comment by scajal** [comment]
I'm still facing this issue in v1.3.0.

**Comment by SwapnilSoni1999** [comment]
same issue here
