### ISSUE TITLE
Error adsbygoogle.push() error: No slot size for availableWidth=0

### ISSUE THREAD

**Issue by yoann54** [nuxt-community/google-adsense-module#21]
this error appear on my browser adsbygoogle.push() error: No slot size for availableWidth=0  but they appear well on the browser.

my ads are responsive, so maybe i didn't them them well. Does anyone has the same problem ?

**Comment by tmorehouse** [comment]
Ensure that your ad container has an explicit width (i.e. in percentages, or absolute pixels based on media queries), and that your CSS is fully loaded before the javascript is loaded.

**Comment by cliffordh** [comment]
Seeing the same thing:

```
<div class="container-fluid">
      <div class="row">
        <div class="hideonmobile text-center col-md-8 offset-md-3">
          <adsbygoogle
            ad-slot="xxx"
          >
          </adsbygoogle>
        </div>
      </div>
    </div>
```

**Comment by CloudMunk** [comment]
I'm also experiencing this problem, has there been any proper solution found to it?
