### ISSUE TITLE
Showing ad all over the website in production.

### ISSUE THREAD

**Issue by sarthaksavvy** [nuxt-community/google-adsense-module#24]
I can sucessfully added adsense ads to nuxt project but when I deploy it on server, then ads are showing on each of the page.

**Comment by maverickpravin** [comment]
same here.. i am using adsense module on just one page. but the ads are displayed on other pages too.

**Comment by tmorehouse** [comment]
Are you placing the ad outside of a `<nuxt-view>` or `<nuxt-child>` component? that would be the only way the ads would stay on page if your route changes, unless you have page level ads enabled (which will show ads at the bottom or top of the page, when google thinks there is an opportunity).

**Comment by sarthaksavvy** [comment]
Hey the problem is with adsense itslef. and its not a problem actually, its adsense auto ad feature.
This feature place ad on your whole website by default.

You need to switch it off from your adsense account. just to to your adsense account and turn every type of ad in your autoad section.
This solves our problem

**Comment by maverickpravin** [comment]
@tmorehouse  i am using single instance in a page component but the ads are being shown on index page as well.
