### ISSUE TITLE
No ads are rendering after generate SSR

### ISSUE THREAD

**Issue by icodefuture** [nuxt-community/google-adsense-module#57]
Added this plugin and configured it with the correct details. Test mode is working perfectly but once I generate  the application it renders <adsbygoogle /> component as it is and even the pagead script is not there in the head section

**Comment by kimulaco** [comment]
I have the same issue too.
Is SSR unsupported?

> - nuxt: ^2.14.4
>     - mode: universal
>     - target: static
> - @nuxtjs/google-adsense: ^1.1.3

Repogitory is [here](https://github.com/kimulaco/kimulaco-blog).

**Comment by kimulaco** [comment]
Sorry. The above was my mistake.
The option key supports `google-adsense`, but I had set it with `googleAdsense`.
I fixed it by changed to `google-adsense`.

**Comment by kimulaco** [comment]
Yes. My problem has been solved.
However, I do not know if the @icodefuture issue is the same.
