### ISSUE TITLE
adsbygoogle.push() error: No slot size for availableWidth=0"

### ISSUE THREAD

**Issue by CloudMunk** [nuxt-community/google-adsense-module#59]
I'm using Vuetify and flexbox, but I keep running into this error.

I've tried setting the parent elements min/max widths/heights, tried adding display:block to the given element and for some reason, I keep getting this error.

**Comment by farnabaz** [comment]
Did you try setting width/height for ad element?  
I think this [question](https://webmasters.stackexchange.com/questions/123615/what-is-a-data-ad-slot-for-google-adsense-and-why-is-inline-styling-required) might help you.
