### ISSUE TITLE
A "noindex,noarchive,nofollow" robots meta is added in final bundle's html

### ISSUE THREAD

**Issue by xinnks** [nuxt-community/google-adsense-module#60]
Issue started when I added the module to my site leading to indexing errors from search engines. The only fix that worked was removing the module from the  #project. #

**Comment by bengineer19** [comment]
Looks like this is the expected behaviour in dev mode? Shouldn't happen in production I expect
https://github.com/nuxt-community/google-adsense-module/blob/c59c02f0b4169430ded76c727a63970f33928d39/lib/module.js#L75-L83

**Comment by xinnks** [comment]
@bengineer19  I was getting this on the production environment, after running ```nuxt generate```.

**Comment by bengineer19** [comment]
Do you have the `test` option enabled?

**Comment by xinnks** [comment]
I disabled it but still had the issue.

**Comment by farnabaz** [comment]
@xinnks Did you find a workaound for the issue? if not could you provide a reprodution sample so we can dig for the solution?

**Comment by xinnks** [comment]
@farnabaz had no more time on hand to work out a solution so I stopped using the plugin altogether and opted for other conventional ways to implement google adsense on my site. When I get the time I might dig deeper into it.

**Comment by bekee** [comment]
@xinnks which plugin did you later use?

**Comment by xinnks** [comment]
@bekee not using any.

**Comment by kovaletsyurii** [comment]
I've had the same issue on my local development build with test: false option configured. On production build all works fine.
