### ISSUE TITLE
not detected by Google Adsense application

### ISSUE THREAD

**Issue by lunafi-evan** [nuxt-community/google-adsense-module#8]
I've enabled this module in a production website that's hosted using a static nuxt deployment. I tried applying to Google Adsense twice and both times the application failed because they were unable to detect the code on the website. I can look at the sources and see the code in an included `<script>` tag, but Google doesn't detect it.

**Comment by tmorehouse** [comment]
I've added in some initialization code for new AdSense accounts (and feature for enabling Page Level ads).

The new release should be available on NPM momentarily

**Comment by tmorehouse** [comment]
Background:  It appears that google needs the following script in `<head>` for detecting new accounts:

```html
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-123456789",
    enable_page_level_ads: true
  });
</script>
```

While existing user accounts do not need this code.
