### ISSUE TITLE
Cannot show ads on SSR

### ISSUE THREAD

**Issue by syskin** [nuxt-community/google-adsense-module#87]
Hi,
I have a SSR nuxtjs application and using this module. I got apply by adsense but cannot display ads (they are not showing).

I try without the module (using the code that give google), and it works.
But if i change page, ads are not showing, it need hot reload on each page.

**Comment by farnabaz** [comment]
Do you confirm that issue still exists in `v1.3.0-rc.1`?

**Comment by farnabaz** [comment]
This should be fixed in [v1.3.0](https://github.com/nuxt-community/google-adsense-module/releases/tag/v1.3.0).  

Feel free to reopen this 🙂
