### ISSUE TITLE
Uncaught P error

### ISSUE THREAD

**Issue by jbty** [nuxt-community/google-adsense-module#94]
Hi,

I try to add addsense module in my app [https://shirime.one](https://shirime.one) and I get this error : 

```js
"adsbygoogle.push() error: Only one 'enable_page_level_ads' allowed per page."
```

my nuxt config : 
```js
'google-adsense': {
  id: 'ca-pub-6212158440227897',
  pageLevelAds: true,
},
```

**Comment by jbty** [comment]
Thanks ! When it's available I give you a feedback

**Comment by jbty** [comment]
@farnabaz Thanks, I have updated to the v1.2.1 but the problem persist :(

**Comment by jbty** [comment]
> @jbty It is sad.
> I will investigate the cause, thank you for quick reply.

Thanks for this module !

**Comment by farnabaz** [comment]
@jbty This should fix in `1.3.0-rc.1`.  
After investigating your application, I found the cause. I released a beta version `1.3.0-rc.1` to ensure correct functionality in real world.  
Really appreciate if you can test the new beta version
```
npm i @nuxtjs/google-adsense@1.3.0-rc.1
```

**Comment by jbty** [comment]
@farnabaz I try this now

**Comment by jbty** [comment]
Nice jobs ! Everything work as exepted 🔥
