### ISSUE TITLE
adsbygoogle.push() error: All ins elements in the … with class=adsbygoogle already have ads in them."

### ISSUE THREAD

**Issue by Fikrifrds** [nuxt-community/google-adsense-module#97]
What cause this error?

**Comment by xaander1** [comment]
@farnabaz  I get the error while using `keep-alive`. Whe you visit the page the first time...works fine. When you navigate to a new url then go back to the old url. The error occurs and the ad disappears. 

I'll see if i can reproduce the issue on CodeSandbox

**Comment by xaander1** [comment]
@farnabaz @Atinux 
Here is a CodeSandBox reproducing the issue.

https://codesandbox.io/s/interesting-liskov-gcevo

**Comment by swsalim** [comment]
@farnabaz @xaander1 I could confirm that the issue is fixed if you're not using `keep-alive`.

But if you do use `keep-alive` like what @xaander1 mentioned, the error still occurs. 

Is there a workaround for it?

**Comment by xaander1** [comment]
@swsalim The issue has been patched by @farnabaz [ check here](https://github.com/nuxt-community/google-adsense-module/pull/107) . However i did notice when yo go back the ads on screen focus tend to disappear...no errors though and more ads can be loaded as you scroll...its better than before.

The workaround i suppose is installing the package from @farnabaz patch branch: `github:nuxt-community/google-adsense-module#farnabaz-patch-1`

Your dependency should look like: 
```
...
"@nuxtjs/google-adsense": "github:nuxt-community/google-adsense-module#farnabaz-patch-1",
...
```
